### PR TITLE
Customized api

### PR DESCRIPTION
**Pull request by AndyJenness**
### Checklist

- [x] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [x] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MINOR* [version update](https://semver.org/)
Unsure, either Minor or Patch. It adds some new functionality but is backwards compatabile.

### Context

`Appetize.io` allows for custom api endpoints, e.g. `@YourBusinessName.appetize.io/v1/apps`. This patch allows for the endpoint and app host name to be customized but defaults to `appetize.io` to not effect current users of this step.

### Changes

- Added `appetize_api`, default = `@api.appetize.io/v1/apps`, to `bitrise.yml` options with descriptions  & defaults
- Added `appetize_host`, default = `appetize.io`,  to `bitrise.yml` options with descriptions  & defaults
- Removed the`apiEndPoint` constant in `client.go`
- Added `apiEndPoint` as a variable to be passed to `NewClient` & `baseURL` in `client.go`
- Added `host` as a variable to be passed to `generateAppURL` in `main.go` 
- Updated tests with new variables

### Testing
I tested in my bitrise setup using the git url for this fork and was successful for both use cases of defaults and setting new parameters.

### CODE REVIEW

**Comment by AndyJenness** [comment]
@ofalvai , hi there, I'm trying to get this PR reviewed but it doesn't look like I can assign a reviewer. Would you be able to assist? Thank you!

**Comment by AndyJenness** [comment]
@BirmacherAkos , I see that you've reviewed for this repo before, do you mind taking a look at this PR?

**Comment by vshah23** [comment]
Hi @AndyJenness we appreciate your contribution to improving this step!

**Review by vshah23 — CHANGES_REQUESTED** [review]
Please run `gofmt` in the project directory.

**Comment by AndyJenness** [comment]
@vshah23 Thanks for reviewing! Sorry, I missed your comment for so long. I've run `gofmt` and updated the files.

**Review by lpusok — APPROVED** [review]

**Pull request merged**
